@startuml

class Utilizator {
    + ID : int
    + Nume : string
    + Prenume : string
    + Email : string
    - HashParola : string
    + InregistratLa: DateTime

    bool VerificareParola(email, parola)
}

class Fisier {
    + Denumire : string
    + Tip : string
    + CreatLa : DateTime
    + Proprietar : Utilizator
    + Dosar : Nullable<Dosar>
    + Impartit : List<Alocare>
    + Editari : List<Editare>
    - Sters : bool

    + void Imparte(Utilizator)
    + void Sterge()
    + void Modifica(Fisier)
}

class Alocare {
    + UtilizatorID : int
    + PermisaEditarea : bool
}

class Editare {
    + UtilizatorID : int
    + Data : DateTime
}

class Dosar {
    + Denumire : string
    + CreatLa : DateTime
    + Proprietar : Utilizator
    + Impartit : List<Alocare>
    + Editari : List<Editare>
    - Sters : bool
    
    + byte[] DescarcareZip()
    + void Sterge()
    + void Modifica(Dosar)
    + void Imparte(Utilizator)
}

Utilizator "1" *-- "*" Fisier
Utilizator "1" *-- "*" Dosar
Dosar "1" *-- "*" Alocare
Dosar "1" *-- "*" Editare
Dosar "1" *-- "*" Fisier
Fisier "1" *-- "*" Alocare
Fisier "1" *-- "*" Editare
@enduml