@startuml

Utilizator --> (Creare cont)
Utilizator --> (Login)
Utilizator --> (Modifica datele)
Utilizator --> (Resetare parola)

rectangle "Proprietar / Imputernicit (total)" as Proprietar {
    Utilizator --> (Adaugare dosar/fisier)
    Utilizator --> (Modificare dosar/fisier)
    Utilizator --> (Stergere dosar/fisier)
    Utilizator --> (Impartire dosar/fisier)
    rectangle "Imputernicit (vizualizare)" as Imputernicit {
        Utilizator ---> (Vizualizare dosar/fisier)
        Utilizator ---> (Descarcare dosar/fisier)
    }
}

@enduml