@startuml

Utilizator --> (Creare cont)
Utilizator --> (Login)
Utilizator --> (Modifica datele)
Utilizator --> (Resetare parola)

rectangle "Proprietar / Imputernicit (total)" as Proprietar {
    Utilizator --> (Adaugare folder/fisier)
    Utilizator --> (Modificare folder/fisier)
    Utilizator --> (Stergere folder/fisier)
    Utilizator --> (Impartire folder/fisier)
    rectangle "Imputernicit (vizualizare)" as Imputernicit {
        Utilizator ---> (Vizualizare folder/fisier)
        Utilizator ---> (Descarcare folder/fisier)
    }
}

@enduml